development:
  host: '127.0.0.1'
  port: 9042
  keyspace: 'schools_dev'
  replication:
    class: 'SimpleStrategy'
    replication_factor: 1

test:
  host: '127.0.0.1'
  port: 9042
  keyspace: 'schools_test'
  replication:
    class: 'SimpleStrategy'
    replication_factor: 1
    
production:
  host: <%= ENV['CASSANDRA_URL'] || '127.0.0.1' %>
  port: 9042
  keyspace: 'schools'
  replication:
    class: 'SimpleStrategy'
    replication_factor: 1
